{
 "title": "Node Drilldown",
 "tags": [ "node" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "hostname", "query": "node_time_seconds" }
  ]
 },
 "panels": [
  {
   "title": "Distro",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(node_uname_info{instance=\"[[hostname]]\"}, \"distro\", \"$1\", \"version\", \"#\\\\d+-(.+)SMP.*\")",
     "legendFormat": "{{distro}}"
    }
   ]
  },
  {
   "title": "Kernel Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(node_uname_info{instance=\"[[hostname]]\"}, \"kernel\", \"$1\", \"release\", \"([0-9]+.[0-9]+.[0-9]+).*\")",
     "legendFormat": "{{kernel}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=\"[[hostname]]\",mode=\"idle\"}[$__interval])) by (instance)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes{instance=\"[[hostname]]\"} / node_memory_MemTotal_bytes{instance=\"[[hostname]]\"}"
    }
   ]
  },
  {
   "title": "Entropy Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_entropy_available_bits{instance=\"[[hostname]]\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=\"[[hostname]]\",mode=\"idle\"}[$__interval])) by (instance)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes{instance=\"[[hostname]]\"} / node_memory_MemTotal_bytes{instance=\"[[hostname]]\"}"
    }
   ]
  },
  {
   "title": "Arch",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_uname_info{instance=\"[[hostname]]\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"[[hostname]]\"} - node_boot_time_seconds{instance=\"[[hostname]]\"}"
    }
   ]
  },
  {
   "title": "Load Average (5m)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{instance=\"[[hostname]]\"} / count(node_cpu_seconds_total{instance=\"[[hostname]]\", mode=\"idle\"}) without (cpu,mode)"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 4 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (irate(node_network_receive_bytes_total{instance=\"[[hostname]]\",device!~\"br-.*\",device!~\"veth.*\",device!~\"docker.\"}[$__interval]) + irate(node_network_transmit_bytes_total{instance=\"[[hostname]]\",device!~\"br-.*\",device!~\"veth.*\",device!~\"docker.\"}[$__interval])) by (instance)"
    }
   ]
  },
  {
   "title": "NTP Offset",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "abs(node_timex_offset_seconds{instance=\"[[hostname]]\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (mode) (irate(node_cpu_seconds_total{instance=\"[[hostname]]\",mode!=\"idle\"}[$__interval]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"[[hostname]]\"} / count(node_cpu_seconds_total{instance=\"[[hostname]]\", mode=\"idle\"}) without (cpu,mode)",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"[[hostname]]\"} / count(node_cpu_seconds_total{instance=\"[[hostname]]\", mode=\"idle\"}) without (cpu,mode)",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=\"[[hostname]]\"} / count(node_cpu_seconds_total{instance=\"[[hostname]]\", mode=\"idle\"}) without (cpu,mode)",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"[[hostname]]\"} - node_memory_MemFree_bytes{instance=\"[[hostname]]\"} - node_memory_Buffers_bytes{instance=\"[[hostname]]\"} - node_memory_Cached_bytes{instance=\"[[hostname]]\"} - node_memory_SwapCached_bytes{instance=\"[[hostname]]\"} - node_memory_Slab_bytes{instance=\"[[hostname]]\"} - node_memory_PageTables_bytes{instance=\"[[hostname]]\"} - node_memory_VmallocUsed_bytes{instance=\"[[hostname]]\"}",
     "legendFormat": "apps"
    },
    {
     "expr": "node_memory_Shmem_bytes{instance=\"[[hostname]]\"}",
     "legendFormat": "shared"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"[[hostname]]\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"[[hostname]]\"}",
     "legendFormat": "buffered"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=\"[[hostname]]\"}",
     "legendFormat": "slab"
    }
   ]
  },
  {
   "title": "Swap IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(node_vmstat_pswpin{instance=\"[[hostname]]\"}[$__interval]) * 4096",
     "legendFormat": "swap in"
    },
    {
     "expr": "increase(node_vmstat_pswpout{instance=\"[[hostname]]\"}[$__interval]) * 4096",
     "legendFormat": "swap out"
    }
   ]
  },
  {
   "title": "Allocated File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=\"[[hostname]]\"}",
     "legendFormat": "descriptors allocated"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_vmstat_pgmajfault{instance=\"[[hostname]]\"}[$__interval]) * 4096",
     "legendFormat": "swap in"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "irate(node_intr_total{instance=\"[[hostname]]\"}[$__interval])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=\"[[hostname]]\"}[$__interval])",
     "legendFormat": "context switches"
    }
   ]
  },
  {
   "title": "Fork Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "irate(node_forks_total{instance=\"[[hostname]]\"}[$__interval])",
     "legendFormat": "forks given"
    }
   ]
  },
  {
   "title": "Disk Read Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"[[hostname]]\",device!~\"dm.+\",device!~\"md.+\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Write Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"[[hostname]]\",device!~\"dm.+\",device!~\"md.+\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"[[hostname]]\",device!~\"br-.*\",device!~\"veth.*\",device!~\"docker.*\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"[[hostname]]\",device!~\"br-.*\",device!~\"veth.*\",device!~\"docker.*\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Established TCP Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"[[hostname]]\"}",
     "legendFormat": "total connections"
    }
   ]
  },
  {
   "title": "UDP Datagrams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=\"[[hostname]]\"}[$__interval])",
     "legendFormat": "in"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=\"[[hostname]]\"}[$__interval])",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Available Entropy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_entropy_available_bits{instance=\"[[hostname]]\"}",
     "legendFormat": "entropy available"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"[[hostname]]\"} - node_boot_time_seconds{instance=\"[[hostname]]\"}",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Login Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (node_logind_sessions{type=\"tty\",instance=\"[[hostname]]\"}) by (class)",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Local Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - 100 * node_filesystem_free_bytes{instance=\"[[hostname]]\",fstype!=\"fuse.lxcfs\",fstype!=\"tmpfs\",fstype!~\"nfs4?\",fstype!=\"zfs\",mountpoint!~\"/run/.*\"}\n/ node_filesystem_size_bytes{instance=\"[[hostname]]\",fstype!=\"fuse.lxcfs\",fstype!=\"tmpfs\",fstype!~\"nfs4?\",fstype!=\"zfs\",mountpoint!~\"/run/.*\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "ZFS Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - 100 * node_filesystem_free_bytes{instance=\"[[hostname]]\",fstype=\"zfs\"}\n/ node_filesystem_size_bytes{instance=\"[[hostname]]\",fstype=\"zfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}