{
 "title": "Timeout overview",
 "description": "For those with little legroom",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(bbb_meetings)", "legendFormat": "Meetings" },
    { "expr": "sum(bbb_meetings_participants)", "legendFormat": "Participants" },
    {
     "expr": "sum(bbb_meetings_video_participants)",
     "legendFormat": "Video feeds"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(bbb_meetings_participants)", "legendFormat": "Participants" },
    { "expr": "sum(bbb_meetings)", "legendFormat": "Meetings" },
    {
     "expr": "sum(bbb_meetings_video_participants)",
     "legendFormat": "Video feeds"
    }
   ]
  },
  {
   "title": "Maximum values",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sum(bbb_meetings_participants)", "legendFormat": "Participants" },
    { "expr": "sum(bbb_meetings)", "legendFormat": "Meetings" },
    {
     "expr": "sum(bbb_meetings_video_participants)",
     "legendFormat": "Video feeds"
    }
   ]
  },
  {
   "title": "Load average (1 minute)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Video Participants",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_meetings_video_participants",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}