{
 "title": "Node Overview",
 "tags": [ "node" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Linux Kernel Versions",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(label_replace(node_uname_info, \"kernel\", \"$1\", \"release\", \"([0-9]+.[0-9]+.[0-9]+).*\")) by (kernel)",
     "legendFormat": "{{kernel}}"
    }
   ]
  },
  {
   "title": "Recent Reboots",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds) / 3600 < 48",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Normalised Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5 / count(node_cpu_seconds_total{mode=\"idle\"}) without (cpu,mode)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total[30s])",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!~\"br-.*\",device!~\"veth.*\",device!~\"docker.*\"}[30s])",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~\"br-.*\",device!~\"veth.*\",device!~\"docker.*\"}[30s])",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - 100 * node_filesystem_free_bytes{fstype!=\"fuse.lxcfs\",fstype!=\"tmpfs\",fstype!~\"nfs4?\",fstype!=\"zfs\"}\n/ node_filesystem_size_bytes{fstype!=\"fuse.lxcfs\",fstype!=\"tmpfs\",fstype!~\"nfs4?\",fstype!=\"zfs\"}",
     "legendFormat": "{{device}} {{instance}}"
    }
   ]
  },
  {
   "title": "NTP Offset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "abs(node_timex_offset_seconds)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Entropy Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_entropy_available_bits", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}